"""empty message

Revision ID: dff6ed61e399
Revises: 254e609ac29c
Create Date: 2019-11-16 20:44:13.102905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dff6ed61e399'
down_revision = '254e609ac29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skincare', sa.Column('condition', sa.String(length=100), nullable=True))
    op.drop_column('skincare', 'problem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skincare', sa.Column('problem', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('skincare', 'condition')
    # ### end Alembic commands ###
